TARGET=lab
BRANCH=run/lab/standard

BRANCHES=(
    bug/kobo-sync
    feat/kobo-sync-removals
    debug/kobo-ts
    debug/kobo-state-locator-logging
    debug/kobo-store-reading-state-locator-logging
    bug/kobo-popup-v2
    feat/series-author-add-shelf
    feat/book-detail-normal-nav
    feat/book-detail-layout
    feat/epub-reader-foliate

    # Lab specific, merge last
    feat/lab-flag
)
