TARGET=lab
BRANCH=run/lab/standard

BRANCHES=(
    bug/kobo-sync
    debug/kobo-ts
    feat/series-author-add-shelf
    feat/book-detail-normal-nav
    feat/book-detail

    # Lab specific, merge last
    feat/lab-flag
)
