TARGET=lab
BRANCH=run/lab/standard

BRANCHES=(
    bug/kobo-sync
    bug/kobo-put-response
    bug/kobo-priority-timestamp  # must follow bug/kobo-put-response
    feat/series-author-add-shelf
    feat/book-detail-normal-nav

    # Lab specific, merge last
    feat/lab-flag
)
